# Starting with schema v12, (2) new config values are available for chunk object prefixes.
# These prefixes can help to avoid rate limiting when using S3 as an object store by better
# parallelizing read/write operations on chunks.
#
# Example chunk key in S3 with these new prefixes: `<user>/<period>/<shard>/<fprint>/<start>:<end>:<checksum>`

schema_config:
  configs:
  - from: 2022-01-01
    store: aws
    object_store: s3
    schema: v12
    index:
      prefix: loki_
    chunk_path_period: 1h
    chunk_path_shard_factor: 2